### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by anirban-mukherjee** [rstudio/reticulate#1139]
As described here (https://github.com/rstudio/tfprobability/issues/139) and here (https://github.com/tensorflow/probability/issues/1500), running the following Python code through reticulate gives a NotImplementedError after the 11th line of the code (the line that calls `tfpl.IndependentNormal`). The model builds correctly. Running the same code through terminal does not give this error.

```
import tensorflow as tf
import tensorflow_probability as tfp
tfkl = tf.keras.layers
tfpl = tfp.layers

input_shape = [28, 28, 1]
encoded_shape = 2

inputs = tf.keras.Input(shape=input_shape)
layer1 = tfkl.Flatten()(inputs)
layer2 = tfkl.Dense(units=10)(layer1)
layer3 = tfkl.Dense(units=tfpl.IndependentNormal.params_size(encoded_shape)) (layer2)
outputs = tfpl.IndependentNormal(event_shape = encoded_shape) (layer3)
model=tf.keras.Model(inputs, outputs)
model.summary()

```

```
> reticulate::py_config()
python:         /Users/anirbanmukherjee/tensorflow-metal/bin/python3
libpython:      /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin/libpython3.8.dylib
pythonhome:     /Users/anirbanmukherjee/tensorflow-metal:/Users/anirbanmukherjee/tensorflow-metal
version:        3.8.12 (default, Oct 22 2021, 18:39:35)  [Clang 13.0.0 (clang-1300.0.29.3)]
numpy:          /Users/anirbanmukherjee/tensorflow-metal/lib/python3.8/site-packages/numpy
numpy_version:  1.22.1
tensorflow_probability:/Users/anirbanmukherjee/tensorflow-metal/lib/python3.8/site-packages/tensorflow_probability

NOTE: Python version was forced by RETICULATE_PYTHON
> sessionInfo()
R version 4.1.2 Patched (2021-12-24 r81416)
Platform: x86_64-apple-darwin21.2.0 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] compiler  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_2.7.0.9000     tfprobability_0.12.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8           lattice_0.20-45      png_0.1-7            zeallot_0.1.0       
 [5] grid_4.1.2           R6_2.5.1             jsonlite_1.7.3       magrittr_2.0.1      
 [9] tfruns_1.5.0         rlang_0.4.12         whisker_0.4          Matrix_1.4-0        
[13] reticulate_1.23-9000 generics_0.1.1       keras_2.7.0.9000     tools_4.1.2         
[17] xfun_0.29            parallel_4.1.2       base64enc_0.1-3      knitr_1.37     
```

**Comment by t-kalinowski** [comment]
Hi, Thanks for filing. I can't reproduce the issue locally:
```
> reticulate::repl_python()
Python 3.8.12 (/Users/tomasz/Library/r-miniconda-arm64/envs/r-reticulate/bin/python)
Reticulate 1.23.9000 REPL -- A Python interpreter in R.
Enter 'exit' or 'quit' to exit the REPL and return to R.
>>> import tensorflow as tf
>>> import tensorflow_probability as tfp
>>> tfkl = tf.keras.layers
>>> tfpl = tfp.layers
>>> 
>>> input_shape = [28, 28, 1]
>>> encoded_shape = 2
>>> 
>>> inputs = tf.keras.Input(shape=input_shape)
>>> layer1 = tfkl.Flatten()(inputs)
>>> layer2 = tfkl.Dense(units=10)(layer1)
Metal device set to: Apple M1 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

2022-01-18 20:22:20.385757: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-01-18 20:22:20.385901: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
>>> layer3 = tfkl.Dense(units=tfpl.IndependentNormal.params_size(encoded_shape)) (layer2)
>>> outputs = tfpl.IndependentNormal(event_shape = encoded_shape) (layer3)
2022-01-18 20:22:20.440204: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
>>> model=tf.keras.Model(inputs, outputs)
>>> model.summary()
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 10)                7850      
                                                                 
 dense_1 (Dense)             (None, 4)                 44        
                                                                 
 independent_normal (Indepen  ((None, 2),              0         
 dentNormal)                  (None, 2))                         
                                                                 
=================================================================
Total params: 7,894
Trainable params: 7,894
Non-trainable params: 0
_________________________________________________________________
>>> 
>>> tfp.__version__
'0.15.0'
>>> tf.__version__
'2.7.0'

```

**Comment by anirban-mukherjee** [comment]
Hmm. I just checked using R on the terminal and I don't get an error there as well. 

I do get the error when using reticulate in R console in RStudio. The other odd thing is that if I close the interactive session started with repl_python then in future interactive sessions with repl_python, I get the error on launch. Specifically, this is what I get in future sessions (after a session in which I got the error).

```
> reticulate::repl_python()
Python 3.8.12 (/Users/anirbanmukherjee/tensorflow-metal/bin/python3)
Reticulate 1.23.9000 REPL -- A Python interpreter in R.
Enter 'exit' or 'quit' to exit the REPL and return to R.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NotImplementedError: 

Detailed traceback:
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pprint.py", line 153, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pprint.py", line 170, in _format
    rep = self._repr(object, context, level)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pprint.py", line 404, in _repr
    repr, readable, recursive = self.format(object, context.copy(),
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pprint.py", line 417, in format
    return _safe_repr(object, context, maxlevels, level, self._sort_dicts)
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pprint.py", line 569, in _safe_repr
    rep = repr(object)
  File "/Users/anirbanmu
```

I get the feeling that this is not a tensorflow issue but rather something to do with reticulate and Python. 

I am using the tensorflow and tensorflow-metal binaries from Apple. These were installed as described here: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by t-kalinowski** [comment]
I can reproduce! The error is raised by a call made by the RStudio IDE. 

Specifically, in [`.rs.reticulate.describeObjectType`](https://github.com/rstudio/rstudio/blob/165196afda6adda393a8e89118bcf463740cb092/src/cpp/session/modules/SessionReticulate.R#L1642), `print.pformat()` is called on the object `outputs`, which in turn calls `__str__`, then `__repr__`, then `TypeSpec._serialize`, which raises the `NotImplementedError`. 

You can reproduce at the terminal (outside the IDE) by attempting to print `outputs`, or manually calling `str(outputs)` or `repr(outputs)`

**Comment by anirban-mukherjee** [comment]
Yep, below is what I get. Should we re-open the issue with TensorFlow Probability?

```
>>> str(outputs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anirbanmukherjee/tensorflow-metal/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 308, in __str__
    return 'KerasTensor(type_spec=%s%s%s%s)' % (
  File "/Users/anirbanmukherjee/tensorflow-metal/lib/python3.8/site-packages/tensorflow/python/framework/type_spec.py", line 336, in __repr__
    return "%s%r" % (type(self).__name__, self._serialize())
  File "/Users/anirbanmukherjee/tensorflow-metal/lib/python3.8/site-packages/keras/engine/keras_tensor.py", line 523, in _serialize
    raise NotImplementedError
NotImplementedError

```

**Comment by t-kalinowski** [comment]
Yes, I think so. Not being able to print an object seems like a bug to me.

**Comment by anirban-mukherjee** [comment]
Ok, will do. I will close here and re-open upstream.
