### ISSUE TITLE
conda run fails if miniconda installation lacks read / write permissions

### ISSUE THREAD

**Issue by kevinushey** [rstudio/reticulate#1152]
From an RSP ticket.

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
 
    Traceback (most recent call last):
      File "/opt/python/miniconda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/python/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/python/miniconda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/python/miniconda/lib/python3.9/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/opt/python/miniconda/lib/python3.9/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/opt/python/miniconda/lib/python3.9/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/python/miniconda/lib/python3.9/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/python/miniconda/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/opt/python/3.7.7/.tmpnmhs8rsf'
 
`$ /opt/python/miniconda/bin/conda run --prefix /opt/python/3.7.7 --no-capture-output python -c import os; print(os.environ['PATH'])`
 
  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/python/miniconda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/opt/R/4.1.1/lib/R/lib:/usr/lib/oracle/19.12/client64/lib/:/lib:/usr/l
                          ocal/lib:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el8_4.x86_64/
                          jre/lib/amd64/server
                  MANPATH=/usr/share/lmod/lmod/share/man:
               MODULEPATH=/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/
                          usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core
                     PATH=/opt/python/3.7.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
                          n:/bin:/usr/lib/rstudio-server/bin/postback
       REQUESTS_CA_BUNDLE=<not set>
   RMARKDOWN_MATHJAX_PATH=/usr/lib/rstudio-server/resources/mathjax-27
   RS_MONITOR_SOCKET_PATH=/var/run/rstudio-server/rstudio-rserver/rserver-monitor.socket
        RS_RPOSTBACK_PATH=/usr/lib/rstudio-server/bin/rpostback
RS_SERVER_LOCAL_SOCKET_PATH=/var/run/rstudio-server/rstudio-rserver/rserver.socket
RS_SERVER_RPC_SOCKET_PATH=/var/run/rstudio-server/rstudio-rserver/session-server-rpc.socket
            SSL_CERT_FILE=<not set>
 
     active environment : None
       user config file : /home/egiel.hanenberg/.condarc
populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/python/miniconda  (read only)
      conda av data dir : /opt/python/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64https://repo.anaconda.com/pkgs/main/noarchhttps://repo.anaconda.com/pkgs/r/linux-64https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/python/miniconda/pkgs
                          /home/egiel.hanenberg/.conda/pkgs
       envs directories : /home/egiel.hanenberg/.conda/envs
                          /opt/python/miniconda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/4.18.0-348.2.1.el8_5.x86_64 centos/8.5.2111 glibc/2.28
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False
 
 
An unexpected error has occurred. Conda has prepared the above report.
 
Error in Sys.setenv(PATH = new_path) : wrong length for argument
In addition: Warning message:
In system2(conda, c("run", in_env, run_args, shQuote(cmd), args),  :
  running command ''/opt/python/miniconda/bin/conda' run --prefix '/opt/python/3.7.7' --no-capture-output 'python' -c "import os; print(os.environ['PATH'])"' had status 1
```

**Comment by t-kalinowski** [comment]
To crosslink, there is are two conda issue about this: https://github.com/conda/conda/issues/10690, 
https://github.com/conda/conda/issues/10066
