### ISSUE TITLE
permission denied when Reticulate looks for Python

### ISSUE THREAD

**Issue by aronatkins** [rstudio/reticulate#1198]
Using the Dockerfile from https://github.com/rstudio/reticulate/issues/1184#issuecomment-1113416358 but without the removal of `/opt/miniconda`, an error occurs, probably caused by permissions issues. The R user is unprivileged, while the Python installations were performed by a privileged user.

Here is the modification to that `Dockerfile`, which does not remove `/opt/miniconda` after installing Python:

```
# Install Python
RUN curl -fsSL -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-py38_4.10.3-Linux-x86_64.sh \
    && chmod 755 miniconda.sh \
    && ./miniconda.sh -b -p /opt/miniconda \
    && /opt/miniconda/bin/conda create --quiet --yes --prefix /opt/python/3.8.12 --channel conda-forge python=3.8.12 \
    && rm -rf miniconda.sh
```

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/miniconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda/lib/python3.8/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/opt/miniconda/lib/python3.8/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/opt/miniconda/lib/python3.8/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/miniconda/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/miniconda/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/opt/python/3.8.12/.tmpaq6e2s1m'

`$ /opt/miniconda/bin/conda run --prefix /opt/python/3.8.12 --no-capture-output python -c import os; print(os.environ['PATH'])`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/miniconda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/opt/R/4.1.3/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-
                          gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/shiny/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __linux=5.10.104=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda  (read only)
      conda av data dir : /opt/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda/pkgs
                          /home/shiny/.conda/pkgs
       envs directories : /home/shiny/.conda/envs
                          /opt/miniconda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.10 Linux/5.10.104-linuxkit ubuntu/20.04.4 glibc/2.31
                UID:GID : 999:999
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Error in Sys.setenv(PATH = new_path) : wrong length for argument
Calls: <Anonymous> -> python_config -> python_munge_path -> Sys.setenv
In addition: Warning message:
In system2(conda, c("run", in_env, run_args, shQuote(cmd), args),  :
  running command ''/opt/miniconda/bin/conda' run --prefix '/opt/python/3.8.12' --no-capture-output 'python' -c "import os; print(os.environ['PATH'])"' had status 1
    ▆
 1. ├─reticulate::py_discover_config()
 2. │ └─reticulate:::python_config(python_version, required_module, forced = "RETICULATE_PYTHON")
 3. │   └─reticulate:::python_munge_path(python)
 4. │     └─base::Sys.setenv(PATH = new_path)
 5. └─global `<fn>`()
```

**Comment by aronatkins** [comment]
This may actually be caused by https://github.com/conda/conda/issues/10690 I'll try using a different miniconda and report back.

**Comment by aronatkins** [comment]
There is not yet a 4.12 miniconda release; the linked issue is resolved in the conda release https://github.com/conda/conda/releases/tag/4.12.0
