### ISSUE TITLE
Subsetting AnnData objects with reticulate

### ISSUE THREAD

**Issue by me-orlov** [rstudio/reticulate#1332]
Hello,

I would like to use reticulate in RStudio for scrnaseq analysis. I am currently going through a tutorial (https://www.sc-best-practices.org/introduction/analysis_tools.html) and am running into the following issue:

```
{python}
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix

counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)

bdata = adata[adata.obs.cell_type == "B"]

Error in repl() : AttributeError: 'AnnData' object has no attribute '_X'

```
There seems to be an issue with how reticulate is handling subsetting for AnnData objects? This does not occur when the same code is ran outside of R. Super new to programming, so I would appreciate any guidance on the issue! I found a similar issue (https://github.com/rstudio/reticulate/issues/1245) but I am not using scanpy. Running with Python 3.10.8 and:

```
R version 4.2.2 (2022-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10     lattice_0.20-45 here_1.0.1      png_0.1-8      
 [5] withr_2.5.0     rprojroot_2.0.3 digest_0.6.31   rappdirs_0.3.3 
 [9] grid_4.2.2      jsonlite_1.8.4  evaluate_0.20   rlang_1.0.6    
[13] cli_3.6.0       rstudioapi_0.14 Matrix_1.5-3    reticulate_1.28
[17] rmarkdown_2.20  tools_4.2.2     yaml_2.3.6      xfun_0.36      
[21] fastmap_1.1.0   compiler_4.2.2  htmltools_0.5.4 knitr_1.41 

```
Thank you for your time.

**Comment by wwang-chcn** [comment]
I encounter the same problem but I think it's an issue for AnnData.
When subset an AnnData object, the _X property won't create in subsetted AnnData object which is need by AnnData.\_\_sizeof\_\_()
```python
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix

counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)

bdata = adata[adata.obs.cell_type == "B"]

import sys
sys.getsizeof(adata)
# 1208741
sys.getsizeof(bdata)
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/sc/arion/work/wangw32/conda-env/envs/giotto_suite_dev/lib/python3.10/site-packages/anndata/_core/anndata.py", line 549, in __sizeof__
#     s = get_size(getattr(self, attr))
# AttributeError: 'AnnData' object has no attribute '_X'. Did you mean: 'X'?
```

**Comment by t-kalinowski** [comment]
I can no longer reproduce the error, I think this has been fixed in AnnData. 
```python
Python 3.12.2 (main, Mar 25 2024, 13:18:57) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
ata as ad
from scipy.sparse import csr_matrix
import sys

counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
data = ad.AnnData(counts)
ct = np.random.choice(["B", "T", "Monocyte"], size=(data.n_obs,))
data.obs["cell_type"] = pd.Categorical(ct)

subsetted_data = data[data.obs.cell_type == "B"]

sys.getsizeof(data)
sys.getsizeof(subsetted_data)>>> import pandas as pd
>>> import anndata as ad
>>> from scipy.sparse import csr_matrix
>>> import sys
>>> 
>>> counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
>>> data = ad.AnnData(counts)
>>> ct = np.random.choice(["B", "T", "Monocyte"], size=(data.n_obs,))
>>> data.obs["cell_type"] = pd.Categorical(ct)
>>> 
>>> subsetted_data = data[data.obs.cell_type == "B"]
>>> 
>>> sys.getsizeof(data)
1192285
>>> sys.getsizeof(subsetted_data)
423614
```

Tested with `anndata.__version__` `'0.10.7'`
