### ISSUE TITLE
`import("asyncio")` fails on Windows

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/reticulate#1478]
Tracking (https://github.com/rstudio/keras/issues/1375), where `reticulate::import("tensorflow")` fails, I was able to narrow down to a smaller reprex using just the standard library:

```
import("asyncio"); #import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  TypeError: the first argument must be callable
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\kalin\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\310~1.11\lib\asyncio\__init__.py", line 47, in <module>
    from .windows_events import *
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\kalin\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\310~1.11\lib\asyncio\windows_events.py", line 25, in <module>
    from . import windows_utils
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\kalin\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\kalin\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\310~1.11\lib\asyncio\windows_utils.py", line 125, in <module>
    class Popen(subprocess.Popen):
TypeError: the first argument must be callable

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("asyncio")
 2.   └─reticulate:::py_module_import(module, convert = convert)
 ```
It looks like this is due to https://github.com/rstudio/reticulate/pull/1458 (reverting the PR fixes the issue).

**Comment by philiporlando** [comment]
I was experiencing similar issues with `reticulate::import("asyncio")` when using `1.32.0`. Upgrading to `1.34.0` resolved this issue.
