### ISSUE TITLE
Timeout when calling  Async python function

### ISSUE THREAD

**Issue by fccoelho** [rstudio/reticulate#1619]
I am trying to call a python async function using reticulate an I am getting a Timeout Error:

here is the code:
```R
library(reticulate)
py_install("mosqlient", envname='r-reticulate')
mosq <- import("mosqlient")
mosq$get_infodengue(disease='dengue', start_date='2010-01-01',end_date='2023-12-31')
```

here is the traceback obtained with `reticulate::py_last_error()`

```python
Traceback (most recent call last):
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/mosqlient/datastore/_infodengue_get_impl.py", line 25, in get_infodengue
    return Infodengue.get(
           ^^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/mosqlient/datastore/infodengue.py", line 29, in get
    return get_all_sync(
           ^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/mosqlient/requests.py", line 123, in get_all_sync
    return asyncio.run(fetch_all())
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/nest_asyncio.py", line 30, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/mosqlient/requests.py", line 111, in fetch_all
    return await get_all(
           ^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/mosqlient/requests.py", line 92, in get_all
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
    future.result()
  File "/usr/lib/python3.12/asyncio/tasks.py", line 316, in __step_run_and_handle_result
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/mosqlient/requests.py", line 47, in aget
    async with session.get(url, params=params, timeout=timeout) as res:
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 971, in start
    with self._timer:
  File "/home/fccoelho/Documentos/Projects_Software/sprint-template/.venv/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
     ▆
  1. ├─IRkernel::main()
  2. │ └─kernel$run()
  3. │   └─IRkernel (local) handle_shell()
  4. │     └─executor$execute(msg)
  5. │       ├─base::tryCatch(...)
  6. │       │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  7. │       │   ├─base (local) tryCatchOne(...)
  8. │       │   │ └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  9. │       │   └─base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
 10. │       │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11. │       │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 12. │       └─evaluate::evaluate(...)
 13. │         └─evaluate:::evaluate_call(...)
 14. │           ├─evaluate (local) timing_fn(...)
 15. │           ├─evaluate (local) handle(...)
 16. │           │ └─base::try(f, silent = TRUE)
 17. │           │   └─base::tryCatch(...)
 18. │           │     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 19. │           │       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 20. │           │         └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 21. │           ├─base::withCallingHandlers(...)
 22. │           ├─base::withVisible(...)
 23. │           └─evaluate:::eval_with_user_handlers(expr, envir, enclos, user_handlers)
 24. │             └─base::eval(expr, envir, enclos)
 25. │               └─base::eval(expr, envir, enclos)
 26. └─mosq$get_infodengue(...)
 27.   └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
See `reticulate::py_last_error()$r_trace$full_call` for more details.
```

**Comment by fccoelho** [comment]
Sorry this was a "real timeout". I tried again and it worked. Closing
