### ISSUE TITLE
Proble with the Python Environment - NameError: name 'flights' is not defined

### ISSUE THREAD

**Issue by gergiu** [rstudio/reticulate#354]
I hope that someone can help me!!

I'm follow the guide in https://rstudio.github.io/reticulate/ but when I need to follow the present command in "Python in R Markdown":
```{python}
import pandas as pd
flights = pd.read_csv("flights.csv", low_memory=False)
flights = flights[flights['dest'] == "ORD"]
flights = flights[['carrier', 'dep_delay', 'arr_delay']]
flights = flights.dropna()
```

when I lunch the command flights = flights[flights['dest'] == "ORD"] this is what I gain:

**Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\RtmpeY2OYK\chunk-code-ad873336498.txt", line 1, in <module>
    flights = flights[flights['dest'] == "ORD"]
NameError: name 'flights' is not defined**

I think the problem is that the object flights isn't saved in the environment..... How can I fix it?

Thank you very much!!

**Comment by skeydan** [comment]
Do you mean you cannot reference flights from another (R) chunk?

This works for me: I'm referencing `flights` as `py$flights` from a subsequent R chunk:

##### this is an R chunk
```{r setup, include=FALSE}
library(reticulate)
```

##### this is python
```{python}
import pandas as pd
flights = pd.read_csv("flights.csv", low_memory=False)
flights = flights[flights['dest'] == "ORD"]
flights = flights[['carrier', 'dep_delay', 'arr_delay']]
flights = flights.dropna()
```

##### this again is R
```{r}
py$flights
```

**Comment by gergiu** [comment]
No, I cannot reference flights from another (python) chunk:

```{python}
import pandas as pd
flights = pd.read_csv("flights.csv", low_memory=False)
```

```{python}
flights = flights[flights['dest'] == "ORD"]
```
**Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\RtmpIJIe4L\chunk-code-116437f73f08.txt", line 1, in <module>
    flights = flights[flights['dest'] == "ORD"]
NameError: name 'flights' is not defined**

**Comment by jjallaire** [comment]
This might be a result of using an older version of RStudio that doesn't support a common session for Python chunks.

**Comment by jjallaire** [comment]
You need at least the current Preview Release of v1.2: https://www.rstudio.com/products/rstudio/download/preview/

**Comment by gergiu** [comment]
Ok, everything fine.

I need to remember me always to have the last version of... 

Have a nice W.E.

**Comment by domi84** [comment]
Hi,
I am having the same issue, just that some days is working, and other not.

R block
```
library(reticulate)
py$test = "test"
py
```
and here I can see the py object with $test, but when I do:

Python block
```
test
```

I got:
_NameError: name 'test' is not defined_

_Detailed traceback:_
  _File "<string>", line 1, in <module>_

I have Rstudio Version 1.3.1093
