### ISSUE TITLE
"import" function cannot make use of bash environment variable

### ISSUE THREAD

**Issue by madcarrot** [rstudio/reticulate#61]
This issue is related to https://github.com/rstudio/tensorflow/issues/121

I'm running on Ubuntu 16.04 with CUDA 8.0 and CUdnn 5.1 installed.

I was trying to run the R Tensorflow package, I had it installed correctly (and working), and then I upgraded the underlying Python Tensorflow package to support GPU. After the upgrade with `pip install --upgrade`, if I run `R` directly from bash, `import("tensorflow")` works correctly, but when I use Rstudio, `import("tensorflow")` returns this error:
```
Error in py_module_import(module, convert = convert) : 
  ImportError: Traceback (most recent call last):
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/user/anaconda3/envs/r-tensorflow/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot op
```

The `libcublas.so.8.0` file is stored in `/usr/local/cuda-8.0/lib64`, and I have my `LD_LIBRARY_PATH` environment variable pointing to it.

I suspected that it might be due to RStudio not having the correct environment variables set up as in my `~/.bashrc`, but 
```
system("python -c 'import tensorflow as tf; sess = tf.InteractiveSession()'")
```
within RStudio would show the correct initialization message.

I also tried to manually set up all the environment variables (e.g. `LD_LIBRARY_PATH`, `CUDA_HOME`, `PATH`) through `Sys.setenv`, and it still doesn't work.

Would you mind helping me with it? I think this will enable a huge performance potential for Tensorflow on RStudio.

**Comment by madcarrot** [comment]
Issue solved in the other thread of discussion
