### ISSUE TITLE
Pip installed but not detected by reticulate py_install

### ISSUE THREAD

**Issue by jaime11** [rstudio/reticulate#832]
Hello, I am trying to load a conda environment into R using reticulate and install a pip package named "mofapy2".

With the conda environment mofa2 having the following packages among others:

```
conda list
# packages in environment at /data/mbp15ja/extra_conda_envs/mofa2:
#
pip                       9.0.1                    py36_1
python                    3.6.2                         0
r                         3.5.0                  mro350_0    r
```

I try to install the pip package named "mofapy2" but get the following error:

```
library(reticulate)
> use_condaenv("mofa2", required = TRUE)
> use_python("/data/mbp15ja/extra_conda_envs/mofa2/bin/python3.8", required = TRUE)
> py_install("mofapy2", envname = "mofa2")
Using virtual environment 'mofa2' ...
Traceback (most recent call last):
  File "/data/mbp15ja/extra_conda_envs/mofa2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/mbp15ja/extra_conda_envs/mofa2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mbp15ja/.virtualenvs/mofa2/lib/python3.8/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # isort:skip # noqa
  File "/home/mbp15ja/.virtualenvs/mofa2/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
ModuleNotFoundError: No module named 'pip._internal.cli'
```

```
py_config()
python:         /data/mbp15ja/extra_conda_envs/mofa2/bin/python3.8
libpython:      /data/mbp15ja/extra_conda_envs/mofa2/lib/libpython3.8.so
pythonhome:     /data/mbp15ja/extra_conda_envs/mofa2:/data/mbp15ja/extra_conda_envs/mofa2
version:        3.8.2 (default, Mar 26 2020, 15:53:00)  [GCC 7.3.0]
numpy:
```

```
sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /data/mbp15ja/extra_conda_envs/mofa2/lib/R/lib/libRblas.so
LAPACK: /data/mbp15ja/extra_conda_envs/mofa2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] reticulate_1.16

loaded via a namespace (and not attached):
[1] compiler_3.5.0  Matrix_1.2-14   Rcpp_1.0.5      grid_3.5.0
[5] jsonlite_1.7.0  lattice_0.20-35
```

**Comment by kevinushey** [comment]
Does reinstalling `pip` fix the problem? 9.0.1 is pretty old IIRC.

**Comment by jaime11** [comment]
I have tried installing in my conda pip 20.2.2-py36_0 anaconda and running the same and I get the same error.
