### ISSUE TITLE
Call Stack issues

### ISSUE THREAD

**Issue by quasiben** [rstudio/reticulate#871]
I am exploring some environment (globalEnv/globals) sharing between R and Python and running into issues which I think come down to how environment scoping.  I could be very wrong about this as I am somewhat out of my depth here.

The following is a concise reproducer of what I am trying to resolve

```R
> inspect$currentframe()
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ValueError: call stack is not deep enough

Detailed traceback:
  File "/home/quasiben/miniconda3/envs/reticulate-r-base/lib/python3.8/inspect.py", line 1510, in currentframe
    return sys._getframe(1) if hasattr(sys, "_getframe") else None
>
```

As the traceback notes, we can also see this with `sys`
```R
> sys <- import("sys")
> sys$`_getframe`()
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ValueError: call stack is not deep enough
```

**Comment by kevinushey** [comment]
I see the same thing in a plain Python REPL:

```
>>> import sys
>>> sys._getframe(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: call stack is not deep enough
```

Presumedly, this functionality would only work if there is already some Python code on the stack (you cannot call it from the top level). Can you provide some more context on what you're trying to do?

**Comment by quasiben** [comment]
I'm trying to handle a case for pandas (possibly cuDF) for the `query` method:


```R
> data.frame(x = c(1,2,3), y = c("a", "b", "c"))
  x y
1 1 a
2 2 b
3 3 c
> df <- data.frame(x = c(1,2,3), y = c("a", "b", "c"))
> df_pd <- r_to_py(df)
> df_pd$query('x > 1')
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ValueError: call stack is not deep enough

Detailed traceback:
  File "/home/quasiben/miniconda3/envs/reticulate-r-base/lib/python3.8/site-packages/pandas/core/frame.py", line 3341, in query
    res = self.eval(expr, **kwargs)
  File "/home/quasiben/miniconda3/envs/reticulate-r-base/lib/python3.8/site-packages/pandas/core/frame.py", line 3471, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/quasiben/miniconda3/envs/reticulate-r-base/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 333, in eval
    env = ensure_scope(
  File "/home/quasiben/miniconda3/envs/reticulate-r-base/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 24, in ensure_scope
    return Scope(
  File "/home/quasiben/miniconda3/envs/reticulate-r-base/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 126, in __init__
    frame = sys._getframe(self.level)
```

I think for the python REPL we should be looking at depth 0 (which is the default):

```python
>>> import sys
>>> sys._getframe()
<frame at 0x7fa6f3e20680, file '<stdin>', line 1, code <module>>
>>> sys._getframe(0)
<frame at 0x7fa6f3d1f040, file '<stdin>', line 1, code <module>>
```

It could be that this is just not possible between embedding Python in R or at least, very challenging.  I'm also looking at how one might push python code on the stack from R and keep it there.

**Comment by quasiben** [comment]
Perhaps another way to run this would be with `py_run_string`:

```R
> df <- data.frame(x = c(1,2,3), y = c("a", "b", "c"))
> df_pd <- r_to_py(df)
> py_run_string("print(r.df_pd.query('x >= 2'))")
     x  y
1  2.0  b
2  3.0  c
```
