### ISSUE TITLE
Reticulate: Document deployment failed with error

### ISSUE THREAD

**Issue by ChaitaC** [rstudio/reticulate#912]
1. devtools::install_github('rstudio/reticulate')
2. Add requirements.txt (empty) file
3. Deploy locally

**Result:**  Document deployment failed with error: An error occurred while running R code. (render-r-code-error)

<details><summary>logs</summary>

```
Preparing to deploy document...DONE
Uploading bundle for document: 26...ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
wheel 0.33.1
DONE
Deploying bundle: 27 for document: 26 ...
[Connect] Building R Markdown document...
[Connect] Bundle requested R version 3.6.1; using /opt/R/3.5.3/lib/R/bin/R which has version 3.5.3
[Connect] 2020/12/18 22:49:15.990689000 Using user agent string: 'RStudio R (3.5.3 x86_64-pc-linux-gnu x86_64 linux-gnu)' 
[Connect] 2020/12/18 22:49:17.531248400 Running on host: connect
[Connect] 2020/12/18 22:49:17.582836700 Linux distribution: Ubuntu 16.04.6 LTS (xenial) 
[Connect] 2020/12/18 22:49:17.585347400 # Validating R library read / write permissions --------------------------------
[Connect] 2020/12/18 22:49:17.586565900 R version: 3.5.3
[Connect] 2020/12/18 22:49:17.620607000 # Validating managed packrat installation --------------------------------------
[Connect] 2020/12/18 22:49:17.628540500 Vendored packrat archive: /connect/ext/R/packrat_0.5.0-26_8753d425f363c420846fe05bcba05e5e9b080bb5.tar.gz
[Connect] 2020/12/18 22:49:17.681422500 Vendored packrat SHA: 8753d425f363c420846fe05bcba05e5e9b080bb5
[Connect] 2020/12/18 22:49:17.741368700 Managed packrat SHA:  8753d425f363c420846fe05bcba05e5e9b080bb5
[Connect] 2020/12/18 22:49:17.827972500 Managed packrat version: 0.5.0.26
[Connect] 2020/12/18 22:49:17.829912800 Managed packrat is up-to-date.
[Connect] 2020/12/18 22:49:17.831634300 # Validating packrat cache read / write permissions ----------------------------
[Connect] 2020/12/18 22:49:18.847119800 Audited package hashes with local packrat installation.
[Connect] 2020/12/18 22:49:18.932718300 # Installing required R packages with `packrat::restore()` ---------------------
[Connect] 2020/12/18 22:49:19.527717200 Installing Rcpp (1.0.5) ... 
[Connect] 2020/12/18 22:49:19.776476100 Using cached Rcpp.
[Connect] 2020/12/18 22:49:19.784199400 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:19.784766700 Installing digest (0.6.26) ... 
[Connect] 2020/12/18 22:49:20.069778300 Using cached digest.
[Connect] 2020/12/18 22:49:20.077269500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:20.077698800 Installing evaluate (0.14) ... 
[Connect] 2020/12/18 22:49:20.328896900 Using cached evaluate.
[Connect] 2020/12/18 22:49:20.336290100 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:20.336894000 Installing glue (1.4.0) ... 
[Connect] 2020/12/18 22:49:20.584736000 Using cached glue.
[Connect] 2020/12/18 22:49:20.591880600 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:20.592404200 Installing highr (0.8) ... 
[Connect] 2020/12/18 22:49:20.837146700 Using cached highr.
[Connect] 2020/12/18 22:49:20.847886500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:20.848157600 Installing jsonlite (1.7.2) ... 
[Connect] 2020/12/18 22:49:21.123347600 Using cached jsonlite.
[Connect] 2020/12/18 22:49:21.095251800 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:21.095495600 Installing lattice (0.20-38) ... 
[Connect] 2020/12/18 22:49:21.344093700 Using cached lattice.
[Connect] 2020/12/18 22:49:21.353090700 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:21.353339600 Installing magrittr (1.5) ... 
[Connect] 2020/12/18 22:49:21.589967700 Using cached magrittr.
[Connect] 2020/12/18 22:49:21.596120300 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:21.596741800 Installing mime (0.9) ... 
[Connect] 2020/12/18 22:49:21.789805600 Using cached mime.
[Connect] 2020/12/18 22:49:21.797980300 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:21.798053800 Installing rappdirs (0.3.1) ... 
[Connect] 2020/12/18 22:49:22.070786900 Using cached rappdirs.
[Connect] 2020/12/18 22:49:22.077378500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:22.077884300 Installing rlang (0.4.8) ... 
[Connect] 2020/12/18 22:49:22.328864900 Using cached rlang.
[Connect] 2020/12/18 22:49:22.335069200 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:22.335197500 Installing stringi (1.4.6) ... 
[Connect] 2020/12/18 22:49:22.672168300 Using cached stringi.
[Connect] 2020/12/18 22:49:22.678749100 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:22.678809200 Installing xfun (0.19) ... 
[Connect] 2020/12/18 22:49:22.940026100 Using cached xfun.
[Connect] 2020/12/18 22:49:22.947229500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:22.948764700 Installing yaml (2.2.1) ... 
[Connect] 2020/12/18 22:49:23.211623200 Using cached yaml.
[Connect] 2020/12/18 22:49:23.215884800 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:23.216156100 Installing Matrix (1.2-17) ... 
[Connect] 2020/12/18 22:49:23.486383300 Using cached Matrix.
[Connect] 2020/12/18 22:49:23.491777300 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:23.491864200 Installing htmltools (0.4.0) ... 
[Connect] 2020/12/18 22:49:23.973021500 Using cached htmltools.
[Connect] 2020/12/18 22:49:23.981344500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:23.982328600 Installing stringr (1.4.0) ... 
[Connect] 2020/12/18 22:49:24.261935300 Using cached stringr.
[Connect] 2020/12/18 22:49:24.270116300 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:24.270783800 Installing markdown (1.1) ... 
[Connect] 2020/12/18 22:49:24.532315100 Using cached markdown.
[Connect] 2020/12/18 22:49:24.545197500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:24.549095500 Installing tinytex (0.22) ... 
[Connect] 2020/12/18 22:49:24.813846900 Using cached tinytex.
[Connect] 2020/12/18 22:49:24.820966500 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:24.820987000 Installing reticulate (1.16) ... 
[Connect] 2020/12/18 22:49:25.391307800 Using cached reticulate.
[Connect] 2020/12/18 22:49:25.398658400 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:25.398875400 Installing knitr (1.28) ... 
[Connect] 2020/12/18 22:49:25.667073100 Using cached knitr.
[Connect] 2020/12/18 22:49:25.675800400 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:25.675948300 Installing rmarkdown (2.5) ... 
[Connect] 2020/12/18 22:49:25.983232200 Using cached rmarkdown.
[Connect] 2020/12/18 22:49:25.992092200 	OK (symlinked cache)
[Connect] 2020/12/18 22:49:26.001895500 Warning message:
[Connect] 2020/12/18 22:49:26.002601100 In packrat::restore(overwrite.dirty = TRUE, prompt = FALSE, restart = FALSE) :
[Connect] 2020/12/18 22:49:26.003179400   The most recent snapshot was generated using R version 3.6.1
[Connect] Completed packrat build against R version: '3.5.3'
[Connect] Launching R Markdown document...
[Connect] 2020/12/18 22:49:28.181333900 Running on host: connect
[Connect] 2020/12/18 22:49:28.223093100 Linux distribution: Ubuntu 16.04.6 LTS (xenial) 
[Connect] 2020/12/18 22:49:28.369004500 Using Packrat dir /connect/mnt/app/packrat/lib/x86_64-pc-linux-gnu/3.5.3
[Connect] 2020/12/18 22:49:28.632102600 LANG: C.UTF-8
[Connect] 2020/12/18 22:49:28.632162200 R version: 3.5.3
[Connect] 2020/12/18 22:49:28.633310600 rmarkdown version: 2.5
[Connect] 2020/12/18 22:49:28.634199200 knitr version: 1.28
[Connect] 2020/12/18 22:49:28.700554200 Warning: The reticulate package is installed but no Python environment is available.
[Connect] 2020/12/18 22:49:28.700703700 Did you forget to set the RETICULATE_PYTHON environment variable in your .Rprofile before publishing?
[Connect] 2020/12/18 22:49:28.704541000 Using pandoc: /connect/ext/pandoc/2.11
[Connect] 2020/12/18 22:49:33.802123400 
[Connect] 2020/12/18 22:49:33.802177200 
[Connect] 2020/12/18 22:49:33.802785100 processing file: test.Rmd
  |.......                                                               |  10%
[Connect] 2020/12/18 22:49:35.109713800   ordinary text without R code
[Connect] 2020/12/18 22:49:35.109743000 
  |..............                                                        |  20%
[Connect] 2020/12/18 22:49:35.122116200 label: unnamed-chunk-1
  |.....................                                                 |  30%
[Connect] 2020/12/18 22:49:39.163363100 label: unnamed-chunk-2 (with options) 
[Connect] 2020/12/18 22:49:39.169208200 List of 1
[Connect] 2020/12/18 22:49:39.170281200  $ engine: chr "python"
[Connect] 2020/12/18 22:49:39.170760200 
[Connect] 2020/12/18 22:49:41.473536800 sh: 1: wheel: not found
  |............................                                          |  40%
[Connect] 2020/12/18 22:49:41.489993600 label: unnamed-chunk-3
  |...................................                                   |  50%
[Connect] 2020/12/18 22:49:41.507115400 label: unnamed-chunk-4
[Connect] 2020/12/18 22:49:41.534483300 sh: 1: wheel: not found
  |..........................................                            |  60%
[Connect] 2020/12/18 22:49:41.543417400 label: unnamed-chunk-5
[Connect] 2020/12/18 22:49:41.566253200 sh: 1: wheel: not found
  |.................................................                     |  70%
[Connect] 2020/12/18 22:49:41.576237300 label: unnamed-chunk-6 (with options) 
[Connect] 2020/12/18 22:49:41.577024200 List of 1
[Connect] 2020/12/18 22:49:41.578259600  $ engine: chr "bash"
[Connect] 2020/12/18 22:49:41.578304700 
[Connect] 2020/12/18 22:49:41.580968900 running: bash  -c 'wheel version || true'
  |........................................................              |  80%
[Connect] 2020/12/18 22:49:41.621282900 label: unnamed-chunk-7 (with options) 
[Connect] 2020/12/18 22:49:41.622184900 List of 1
[Connect] 2020/12/18 22:49:41.623029800  $ engine: chr "python"
[Connect] 2020/12/18 22:49:41.623053200 
  |...............................................................       |  90%
[Connect] 2020/12/18 22:49:41.679322700 label: unnamed-chunk-8
  |......................................................................| 100%
[Connect] 2020/12/18 22:49:41.695520800 label: unnamed-chunk-9 (with options) 
[Connect] 2020/12/18 22:49:41.696363800 List of 1
[Connect] 2020/12/18 22:49:41.698181000  $ engine: chr "python"
[Connect] 2020/12/18 22:49:41.698604600 
[Connect] 2020/12/18 22:49:41.800286500 Quitting from lines 38-44 (test.Rmd) 
[Connect] 2020/12/18 22:49:41.800341200 Error in py_call_impl(callable, dots$args, dots$keywords) : 
[Connect] 2020/12/18 22:49:41.801398800   FileNotFoundError: [Errno 2] No such file or directory: 'wheel'
[Connect] 2020/12/18 22:49:41.802061100 
[Connect] 2020/12/18 22:49:41.802940500 Detailed traceback: 
[Connect] 2020/12/18 22:49:41.804327800 
[Connect] 2020/12/18 22:49:41.803756700   File "<string>", line 1, in <module>
[Connect] 2020/12/18 22:49:41.805373600   File "/opt/python/3.8.2/lib/python3.8/subprocess.py", line 854, in __init__
[Connect] 2020/12/18 22:49:41.806157300     self._execute_child(args, executable, preexec_fn, close_fds,
[Connect] 2020/12/18 22:49:41.807077300   File "/opt/python/3.8.2/lib/python3.8/subprocess.py", line 1702, in _execute_child
[Connect] 2020/12/18 22:49:41.807810200     raise child_exception_type(errno_num, err_msg, err_filename)
[Connect] 2020/12/18 22:49:41.808362100 Calls: local ... py_capture_output -> force -> <Anonymous> -> py_call_impl
[Connect] 2020/12/18 22:49:41.811161300 Execution halted
[Connect] 2020/12/18 22:49:41.801456400 Error code: render-r-code-error
[Connect] An error occurred while running R code.
[Connect] Possible causes:
[Connect] * There is a bug in the R code being deployed.
[Connect] * The R code depends on conditions that are not present in Connect.
[Connect] * The R code depends on a version of R that is not configured in Connect.
[Connect] 
[Connect] Possible solutions:
[Connect] * Correct bugs in the R code, then deploy the corrected content.
  - The document rendering log in Connect contains details of the error.
  - Knitting the document in the RStudio IDE may also be helpful for debugging.
[Connect] * Install a version of R on the Connect server that matches the one being used by the client computer, then redeploy the content. You can identify the required R version from the log messages above, which will contain an entry similar to this:
  > Bundle requested R version 3.5.0; using /usr/lib/R/bin/R which has version 3.4.4
  In this example, the client computer has R 3.5.0 and the Connect server has R version 3.4.4. The recommended solution would be to install R version 3.5.0 on the Connect server alonside the existing 3.4.4 installation.
[Connect] * If you have previously published this content, viewers will continue to see the last successful output until the error is resolved by republishing.
[Connect] 
[Connect] References:
[Connect] * https://docs.rstudio.com/connect/user/content-settings/#content-logs
[Connect] * https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio
[Connect] * https://support.rstudio.com/hc/en-us/articles/229998627-Why-does-my-app-work-locally-but-not-on-my-RStudio-Connect-server
[Connect] * https://docs.rstudio.com/connect/admin/getting-started/#installation
[Connect] 
[Connect] 2020/12/18 22:49:41.801456400 Additional data:
[Connect] Expression: 'py_call_impl(callable, dots$args, dots$keywords)'
[Connect] Message: 'FileNotFoundError: [Errno 2] No such file or directory: 'wheel''
[Connect] Found in the following log entry:
[Connect] 2020/12/18 22:49:41.800341200 Error in py_call_impl(callable, dots$args, dots$keywords) : 
Document deployment failed with error: An error occurred while running R code. (render-r-code-error)
```
</details>

**Comment by kevinushey** [comment]
Can you share the document / application you were deploying as well?

**Comment by kevinushey** [comment]
I believe this should already be resolved in the development version of `reticulate`.
